apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookkeeper
  labels:
    app: bookkeeper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookkeeper
  serviceName: "bookkeeper"
  template:
    metadata:
      labels:
        app: bookkeeper
    spec:
      containers:
      - name: bookkeeper
        image: ttbb/bookkeeper:mate
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2G
            cpu: 1000m
          requests:
            memory: 2G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name: SERVICE_NAME
          value: "bookkeeper"
        - name: ZK_ADDR
          value: "zookeeper-0.zookeeper:2181,zookeeper-1.zookeeper:2181,zookeeper-2.zookeeper:2181"
        - name: META_DATA_SERVICE_URI
          value: "zookeeper-0.zookeeper:2181;zookeeper-1.zookeeper:2181;zookeeper-2.zookeeper:2181"
        - name: CLUSTER_ENABLE
          value: "true"    
        - name: REMOTE_MODE
          value: "false"
        