apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-shard-2
  labels:
    app: mongo-shard-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-shard-2
  serviceName: "mongo-shard-2"
  template:
    metadata:
      labels:
        app: mongo-shard-2
    spec:
      containers:
      - name: mongo-shard-2
        image: ttbb/mongo:shard
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2G
            cpu: 2000m
          requests:
            memory: 2G
            cpu: 2000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name