apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-worker
  labels:
    app: flink-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink-worker
  template:
    metadata:
      labels:
        app: flink-worker
    spec:
      containers:
      - name: flink-worker
        image: ttbb/flink:worker
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2G
            cpu: 1000m
          requests:
            memory: 2G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name