apiVersion: batch/v1
kind: Job
metadata:
  name: bk-init
spec:
  template:
    spec:
      containers:
        - name: bk-init
          image: ttbb/bookkeeper:mate
          imagePullPolicy: Always
          env:
            - name: ZK_ADDR
              value: "zookeeper-0.zookeeper:2181,zookeeper-1.zookeeper:2181,zookeeper-2.zookeeper:2181"
            - name: META_DATA_SERVICE_URI
              value: "zookeeper-0.zookeeper:2181;zookeeper-1.zookeeper:2181;zookeeper-2.zookeeper:2181"              
            - name: CLUSTER_ENABLE
              value: "true"
            - name: CLUSTER_INIT
              value: "true"
            - name: REMOTE_MODE
              value: "false"
      restartPolicy: Never
