apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-name
  labels:
    app: hadoop-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hadoop-name
  template:
    metadata:
      labels:
        app: hadoop-name
    spec:
      containers:
      - name: hadoop-name
        image: ttbb/hadoop:name
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2G
            cpu: 1000m
          requests:
            memory: 2G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name