apiVersion: v1
kind: Service
metadata:
  name: flink-master
spec:
  selector:
    app: flink-master
  clusterIP: None
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 8081
      name: flink-master-ui
    - protocol: TCP
      port: 6123
      name: flink-master-rpc