apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  serviceName: "zookeeper"
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: ttbb/zookeeper:mate
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512M
            cpu: 250m
          requests:
            memory: 512M
            cpu: 250m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name: SERVICE_NAME
          value: "ZooKeeper"
        - name: ZOOKEEPER_NUM
          value: "3"
        - name: CLUSTER_ENABLE
          value: "true"
        - name: REMOTE_MODE
          value: "false"