apiVersion: v1
kind: Service
metadata:
  name: mongo-shard-1
spec:
  selector:
    app: mongo-shard-1
  clusterIP: None
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 27019
      name: mongo-shard-1