apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  clusterIP: None
  sessionAffinity: None
  publishNotReadyAddresses: true
  ports:
    - protocol: TCP
      port: 9000
      name: server