apiVersion: v1
kind: Service
metadata:
  name: pulsar
spec:
  selector:
    app: pulsar
  clusterIP: None
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 6650
      name: pulsar-tcp
    - protocol: TCP
      port: 8080
      name: pulsar-http