apiVersion: v1
kind: Service
metadata:
  name: hadoop-name
spec:
  selector:
    app: hadoop-name
  clusterIP: None
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 9000
      name: hadoop-rpc
    - protocol: TCP
      port: 9870
      name: hadoop-portal