apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-data
  labels:
    app: hadoop-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-data
  serviceName: "hadoop-data"
  template:
    metadata:
      labels:
        app: hadoop-data
    spec:
      containers:
      - name: hadoop-data
        image: ttbb/hadoop:data
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2G
            cpu: 1000m
          requests:
            memory: 2G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name