apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar
  labels:
    app: pulsar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pulsar
  template:
    metadata:
      labels:
        app: pulsar
    spec:
      containers:
      - name: pulsar
        image: ttbb/pulsar:mate
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2G
            cpu: 1000m
          requests:
            memory: 2G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name: ZK_ADDR
          value: "zookeeper-0.zookeeper:2181,zookeeper-1.zookeeper:2181,zookeeper-2.zookeeper:2181"  
        - name: CLUSTER_ENABLE
          value: "true" 
        - name: PULSAR_ROLE
          value: "broker"     
        - name: REMOTE_MODE
          value: "false"
  