apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink
  labels:
    app: flink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
  template:
    metadata:
      labels:
        app: flink
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: flink
        image: ttbb/flink:mate
        imagePullPolicy: Always
        resources:
          limits:
            memory: 4G
            cpu: 1000m
          requests:
            memory: 4G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name: PS1
          value: '[\u@flink@\W]\$ '