apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotdb
  labels:
    app: iotdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotdb
  template:
    metadata:
      labels:
        app: iotdb
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: iotdb
        image: ttbb/iotdb:stand-alone
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2G
            cpu: 1000m
          requests:
            memory: 2G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name: PS1
          value: '[\u@iotdb@\W]\$ '