apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricbeat
  labels:
    app: metricbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricbeat
  template:
    metadata:
      labels:
        app: metricbeat
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: metricbeat
        image: ttbb/metricbeat:mate
        volumeMounts:
          - name: procfs
            mountPath: /proc
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2G
            cpu: 1000m
          requests:
            memory: 2G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name 
        - name: PROM_HOST
          value: "localhost"
        - name: ES_HOST
          value: "localhost"
        - name: INFLUX_HOST
          value: "localhost"
        - name: PS1
          value: '[\u@metricbeat@\W]\$ '
      volumes:
      - name: procfs
        hostPath:
          path: /hostfs