apiVersion: apps/v1
kind: Deployment
metadata:
  name: network
  labels:
    app: network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network
  template:
    metadata:
      labels:
        app: network
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: network
        image: ttbb/base:network
        imagePullPolicy: Always
        command:
          - tail
          - '-f'
          - /dev/null
        resources:
          limits:
            memory: 2G
            cpu: 1000m
          requests:
            memory: 2G
            cpu: 1000m
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - DAC_OVERRIDE
              - SETGID
              - SETUID
              - CHOWN
              - FOWNER
              - KILL
              - SYS_ADMIN
            drop:
              - ALL
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name: PS1
          value: '[\u@network@\W]\$ '