apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: telegraf
        image: ttbb/telegraf:nake
        command:
          - tail
          - '-f'
          - /dev/null
        volumeMounts:
          - mountPath: /opt/sh/collect/log
            name: sh-log
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2G
            cpu: 1000m
          requests:
            memory: 2G
            cpu: 1000m
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name 
        - name: PS1
          value: '[\u@telegraf@\W]\$ '
      volumes:
      - name: sh-log
        hostPath:
          path: /opt/sh/log  