apiVersion: v1
kind: Service
metadata:
  name: glusterfs
spec:
  selector:
    app: glusterfs
  clusterIP: None
  sessionAffinity: None
  publishNotReadyAddresses: true
  ports:
    - protocol: TCP
      port: 24007
      name: server